 version: "3.8"
services:
  db:
    image: mysql
    volumes:
      - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:latest
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    container_name: api_doodle
    image: doodleback
    command: [""]
    restart: always
  front:
    container_name: front_doodle
    image: doodlefront
    ports:
      - 90:80
    volumes:

